CREATE TABLE IF NOT EXISTS tickets
(
    ticket_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name varchar(255),
    route_id    varchar(255),
    payment_id  varchar(255),
    status      varchar(255)
);
