DROP TABLE IF EXISTS routes;

CREATE TABLE routes
(
    route_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure      varchar(255),
    departure_time timestamp,
    destination    varchar(255),
    destination_time timestamp,
    price          numeric(19, 2),
    tickets_amount integer
);
